from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVER_ROOT = ROOT / "server"
sys.path.insert(0, str(SERVER_ROOT))

from app.db import models  # noqa: F401
from app.db.base import Base
from app.db.repositories import engine_repository
from app.db.repositories import user_repository
from app.db.session import SessionLocal
from app.db.session import engine
from app.services.schema_service import ensure_schema
from app.services.seed_service import ensure_admin
from app.services.seed_service import ensure_roles
from app.services.storage_service import ensure_storage_dir
from app.services.storage_service import sha256_for_file


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Add dummy engines to the OpenELO database.")
    parser.add_argument("--count", type=int, default=50, help="Number of dummy engines to create.")
    parser.add_argument("--prefix", default="Dummy Engine", help="Engine name prefix.")
    parser.add_argument("--versions", type=int, default=3, help="Versions to create per engine.")
    parser.add_argument(
        "--owner",
        default="admin",
        help="Username that should be added as owner for new engines.",
    )
    return parser.parse_args()


def next_available_engine_name(db, prefix: str, start_index: int) -> tuple[str, int]:
    index = start_index
    while True:
        name = f"{prefix} {index:03d}"
        if engine_repository.get_public_engine_by_slug(db, engine_repository.slugify(name)) is None:
            return name, index
        index += 1


def create_dummy_artifact(db, version, system_name: str = "linux") -> None:
    file_name = f"{version.engine.slug}-{version.version_name}-{system_name}.sh"
    if any(artifact.file_name == file_name for artifact in version.artifacts):
        return

    target_dir = ensure_storage_dir(SERVER_ROOT / "data" / "dummy" / "artifacts" / str(version.id))
    artifact_path = target_dir / file_name
    artifact_path.write_text(
        "#!/usr/bin/env bash\n"
        f"echo 'Dummy artifact for {version.engine.name} {version.version_name} on {system_name}'\n",
        encoding="utf-8",
    )
    artifact_path.chmod(0o755)
    engine_repository.create_artifact(
        db=db,
        version=version,
        system_name=system_name,
        file_name=file_name,
        file_path=str(artifact_path),
        content_hash=sha256_for_file(artifact_path),
        required_cpu_flags=[],
    )


def main() -> None:
    args = parse_args()
    if args.count <= 0:
        raise SystemExit("--count must be greater than 0")
    if args.versions <= 0:
        raise SystemExit("--versions must be greater than 0")

    Base.metadata.create_all(bind=engine)
    ensure_schema(engine)

    db = SessionLocal()
    try:
        ensure_roles(db)
        ensure_admin(db)

        owner = user_repository.get_user_by_username(db, args.owner)
        if owner is None:
            raise SystemExit(f"Owner '{args.owner}' not found")

        created_engines = []
        next_index = 1
        for _ in range(args.count):
            engine_name, index = next_available_engine_name(db, args.prefix, next_index)
            engine_record = engine_repository.create_engine(
                db=db,
                owner_user_ids=[owner.id],
                name=engine_name,
                description=f"{engine_name} generated by scripts/add_dummy_engines.py",
                protocol="uci",
            )
            for version_index in range(1, args.versions + 1):
                version = engine_repository.create_version(db, engine_record, f"v{version_index}")
                create_dummy_artifact(db, version, "linux")
            created_engines.append(engine_record)
            next_index = index + 1

        print(f"Created {len(created_engines)} dummy engines.")
        print(f"Owner    : {owner.username}")
        print(f"Versions : {args.versions}")
        print()
        for item in created_engines[:10]:
            print(f"- {item.name}")
        if len(created_engines) > 10:
            print(f"... and {len(created_engines) - 10} more")
    finally:
        db.close()


if __name__ == "__main__":
    main()
